// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"detect-agent/internal/biz"
	"detect-agent/internal/conf"
	"detect-agent/internal/grpc_client"
	"detect-agent/internal/pkg/franz-kafka"
	"detect-agent/internal/server"
	"detect-agent/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(nacos *conf.Nacos, logger log.Logger) (*kratos.App, func(), error) {
	batchService := service.NewBatchService(logger)
	grpcServer := server.NewGRPCServer(batchService, logger)
	discovery := server.NewDiscoveryEngine(nacos, logger)
	client, cleanup, err := grpc_client.NewClient(discovery, logger)
	if err != nil {
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(batchService, client, logger)
	producerConfig := server.NewKafkaProducerConfig()
	kafkaProducer, err := franz_kafka.NewKafkaProducer(producerConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	batchDetectHandler := biz.NewBatchDetectHandler(logger, kafkaProducer)
	kafkaServer := server.NewKafkaServer(batchDetectHandler, logger)
	registrar := server.NewRegistryEngine(nacos, logger)
	app := newApp(logger, grpcServer, httpServer, kafkaServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
